<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ccoretest" nsURI="http://com.cubemonstergames/UnityCMF/CCoreTest"
    nsPrefix="ccoretest">
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eAnnotations source="http://com.cubemonstergames/UnityCMF">
      <details key="hasView" value="true"/>
    </eAnnotations>
    <eOperations name="operation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossReference" eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossReferenceSet" upperBound="-1"
        eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="crossReferenceField" upperBound="-1"
        eType="#//FieldContent">
      <eAnnotations source="http://com.cubemonstergames/UnityCMF">
        <details key="Dimensions" value="5,7"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composition" eType="#//Content"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositionSet" upperBound="-1"
        eType="#//Content" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositionField" upperBound="-1"
        eType="#//FieldContent" containment="true">
      <eAnnotations source="http://com.cubemonstergames/UnityCMF">
        <details key="Dimensions" value="5,7"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//Content"
        containment="true">
      <eAnnotations source="http://com.cubemonstergames/UnityCMF">
        <details key="Instances" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceSet" upperBound="5"
        eType="#//Content" containment="true">
      <eAnnotations source="http://com.cubemonstergames/UnityCMF">
        <details key="Instances" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceField" upperBound="-1"
        eType="#//FieldContent" containment="true">
      <eAnnotations source="http://com.cubemonstergames/UnityCMF">
        <details key="Instances" value="true"/>
        <details key="Dimensions" value="5,7"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content" eSuperTypes="#//Interface">
    <eAnnotations source="http://com.cubemonstergames/UnityCMF">
      <details key="hasView" value="true"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true" interface="true">
    <eOperations name="operation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldContent" eSuperTypes="CCore.ecore#//C2DFieldElement"/>
</ecore:EPackage>
