<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ccore" nsURI="http://com.cubemonstergames/UnityCMF/CCore" nsPrefix="ccore">
  <eClassifiers xsi:type="ecore:EClass" name="C2DFieldElement" abstract="true">
    <eOperations name="Neighbor" eType="#//Direction">
      <eParameters name="other" eType="#//C2DFieldElement"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="none"/>
    <eLiterals name="left" value="1"/>
    <eLiterals name="top" value="2"/>
    <eLiterals name="right" value="3"/>
    <eLiterals name="bottom" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CAction" instanceClassName="java.lang.Object">
    <eAnnotations source="http://com.cubemonstergames/UnityCMF">
      <details key="CInstanceClass" value="UnityCMF.CCore.CAction"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
