<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kmm" nsURI="http://kmm/1.0" nsPrefix="kmm">
  <eClassifiers xsi:type="ecore:EClass" name="Tile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onCurrentPath" eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onOldPath" eType="#//Direction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stats">
    <eAnnotations source="http://cubemonstergames.com/UnityCMF">
      <details key="hasView" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kathisLove" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markusLove" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="money" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="experience" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eOperations name="move" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="tile" eType="#//Tile"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stats" lowerBound="1" eType="#//Stats"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentPath" upperBound="-1"
        eType="#//Move" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tiles" upperBound="-1"
        eType="#//Tile" containment="true">
      <eAnnotations source="http://com.cubemonstergames/UnityCMF">
        <details key="2DField" value="9,11"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentTile" eType="#//Tile"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldPath" upperBound="-1"
        eType="#//Move" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eOperations name="apply"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Door" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CAction" instanceClassName="java.lang.Object">
    <eAnnotations source="http://com.cubemonstergames/UnityCMF">
      <details key="CInstanceClass" value="UnityCMF.CCore.CAction"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Move">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actions" upperBound="-1"
        eType="#//CAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tile" eType="#//Tile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="none"/>
    <eLiterals name="left" value="1"/>
    <eLiterals name="top" value="2"/>
    <eLiterals name="right" value="3"/>
    <eLiterals name="bottom" value="4"/>
  </eClassifiers>
</ecore:EPackage>
