<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kmm" nsURI="http://kmm/1.0" nsPrefix="kmm">
  <eClassifiers xsi:type="ecore:EClass" name="Tile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tiles" upperBound="-1"
        eType="#//Tile" containment="true">
      <eAnnotations source="http://com.cubemonstergames/UnityCMF">
        <details key="field" value="9,11"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stats">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kathisLove" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markusLove" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="money" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="experience" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="board" lowerBound="1" eType="#//Board"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stats" lowerBound="1" eType="#//Stats"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" eType="#//Entity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Door" eSuperTypes="#//Entity"/>
</ecore:EPackage>
